nuts/auth/urls.py
from django.urls import path

from auth.views import (
    IndividualRegistrationView,
    BusinessRegistrationView,
    CustomerLoginView,
    CustomerForgotPasswordView,
    CustomerResetPasswordView,
    CustomerLogoutView
)

app_name = 'custom_auth'

urlpatterns = [
    path(
        route="registration/individual/",
        view=IndividualRegistrationView.as_view(),
        name="individual-registration"
    ),
    path(
        route="registration/business/",
        view=BusinessRegistrationView.as_view(),
        name="business-registration"
    ),
    path(
        route="login/",
        view=CustomerLoginView.as_view(),
        name="login"
    ),
    path(
        route="forgot-password/",
        view=CustomerForgotPasswordView.as_view(),
        name="forgot-password"
    ),
    path(
        route="reset-password/",
        view=CustomerResetPasswordView.as_view(),
        name="reset-password"
    ),
    path(
        route="logout/",
        view=CustomerLogoutView.as_view(),
        name="logout"
    )
]

nuts/cart/urls.py
from django.urls import path

from cart.views import (
    CartAddItemView,
    CartUpdateItemView,
    CartPopupView,
    CartCounterView,
    CartTableView
)

app_name = 'cart'

urlpatterns = [
    path('add-item/<int:product_id>/', CartAddItemView.as_view(), name='add-item'),
    path('update-item/<int:item_id>/<str:action>', CartUpdateItemView.as_view(), name='update-item'),
    path('popup/', CartPopupView.as_view(), name='popup'),
    path('counter/', CartCounterView.as_view(), name='counter'),
    path('table/', CartTableView.as_view(), name='table')
]

nuts/cart/models.py
from django.db import models
from django.core.validators import MinValueValidator

from wagtail.models import Page

from cart.managers import CartManager

class CartPage(Page):
    parent_page_types = ['home.HomePage']
    subpage_types = ['orders.OrderCheckoutPage']
    max_count = 1

    template="cart.html"

    class Meta:
        verbose_name = "Cart page"


class Cart(models.Model):
    id = models.BigAutoField(primary_key=True)
    session_key = models.CharField(max_length=40, null=True, blank=True, db_index=True)
    customer = models.ForeignKey('users.CustomerProfile', on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CartManager()


class CartItem(models.Model):
    id = models.BigAutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey('products.Product', on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

nuts/cart/views.py
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render

from products.models import Product

from cart.models import Cart, CartItem

from shop.models import ShopPage

from auth.models import RegisterPage, LoginPage

from orders.models import OrderCheckoutPage

class CartAddItemView(View):
    def post(self, request, product_id):
        product = Product.objects.get(id=product_id)

        if request.user.is_authenticated and hasattr(request.user, "customer_profile"):
            cart, _ = Cart.objects.get_or_create(
                customer=request.user.customer_profile,
                is_active=True,
            )
        else:
            if not request.session.session_key:
                request.session.create()
            cart, _ = Cart.objects.get_or_create(
                session_key=request.session.session_key,
                is_active=True
            )

        item, created = CartItem.objects.get_or_create(cart=cart, product=product, defaults={'quantity': 1})

        if not created:
            item.quantity += 1
            item.save()
        else:
            item.quantity = 1
            item.save()

        response = HttpResponse()
        response['HX-Trigger'] = 'cartUpdated'
        return response


class CartUpdateItemView(View):
    def post(self, request, item_id, action):
        item = CartItem.objects.get(id=item_id)

        if action == 'plus':
            item.quantity += 1
            item.save()

        elif action == 'minus':
            if item.quantity > 1:
                item.quantity -= 1
                item.save()
            else:
                item.delete()

        elif action == 'remove':
            item.delete()

        response = HttpResponse()
        response['HX-Trigger'] = 'cartUpdated'
        return response


class CartPopupView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)
        return render(request, "includes/cart/popup_content.html", {"cart": cart})


class CartCounterView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)
        count = getattr(cart, 'cart_items_count', 0) or 0
        return HttpResponse(str(count))


class CartTableView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)

        shop_page = ShopPage.objects.live().first()
        login_page = LoginPage.objects.live().first()
        register_page = RegisterPage.objects.live().first()
        checkout_page = OrderCheckoutPage.objects.live().first()

        return render(
            request,
            "includes/cart/table.html",
            {
                "cart": cart,
                "shop_page": shop_page,
                "login_page": login_page,
                "register_page": register_page,
                "checkout_page": checkout_page
            }
        )

templates/includes/cart/content.html
{% if is_htmx %}
<span id="cart-counter" hx-swap-oob="innerHTML">
    {{ cart.cart_items_count|default:0 }}
</span>
{% endif %}
<div class="wrap" id="cart-content">
    {% if cart and cart.items.all %}
    {% for item in cart.items.all %}
    <div class="popup__cart_item">
        <div class="row align-items-center no-gutters item_row">
            <div class="col-md-5 col-12">
                <div class="item_title">
                    <p>{{ item.product.name }}</p>
                </div>
            </div>
            <div class="col-md-7 col-12">
                <div class="row align-items-center no-gutters">
                    <div class="col-6">
                        <div class="item_quantity">
                            <button type="button" class="quantity_minus"
                                    hx-post="{% url 'cart:update-item' item.id 'minus' %}"
                                    hx-target="#cart-content"
                                    hx-swap="outerHTML"
                                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-qty-left"></i>
                            </button>
                            <input type="text" name="quantity" value="{{ item.quantity }}" readonly
                                   class="quantity_input">
                            <button type="button" class="quantity_plus"
                                    hx-post="{% url 'cart:update-item' item.id 'plus' %}"
                                    hx-target="#cart-content"
                                    hx-swap="outerHTML"
                                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-qty-right"></i>
                            </button>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="item_sum">
                            <p>{{ item.item_total|floatformat:0 }} <span>грн.</span></p>
                        </div>
                    </div>
                    <div class="col-1">
                        <div class="item_close">
                            <a href="#"
                               hx-post="{% url 'cart:update-item' item.id 'remove' %}"
                               hx-target="#cart-content"
                               hx-swap="outerHTML"
                               hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-close-button"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="popup__cart_sum">
        <div class="sum_item">
            <div class="sum_item_title"><p>Всего </p></div>
            <div class="sum_item_new">
                <p>{{ cart.cart_total|floatformat:0 }} <i>грн.</i></p>
            </div>
        </div>
        <div class="sum_item">
            <div class="sum_item_button">
                <a href="#" class="button">Перейти в корзину</a>
            </div>
        </div>
    </div>
    {% else %}
    <div class="popup__cart_clean">
        <p>Ваша корзина пуста</p>
    </div>
    {% endif %}
</div>

templates/includes/cart/popup_container.html
<div class="container pr">
    <div
            class="popup__cart"
            hx-get="{% url 'cart:popup' %}"
            hx-trigger="cartUpdated from:body"
    >
        <div>
            {% include "includes/cart/popup_content.html" %}
        </div>
    </div>
</div>

templates/includes/cart/popup_content.html
{% load wagtailcore_tags i18n %}
<div class="wrap" id="cart-content">
    {% if cart and cart.items.all %}
    {% for item in cart.items.all %}
    <div class="popup__cart_item">
        <div class="row align-items-center no-gutters item_row">
            <div class="col-md-5 col-12">
                <div class="item_title">
                    <p>{{ item.product.name }}</p>
                </div>
            </div>
            <div class="col-md-7 col-12">
                <div class="row align-items-center no-gutters">
                    <div class="col-6">
                        <div class="item_quantity">
                            <button
                                    type="button" class="quantity_minus"
                                    hx-post="{% url 'cart:update-item' item.id 'minus' %}"
                                    hx-swap="none"
                                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-qty-left"></i>
                            </button>
                            <input type="text" name="quantity" value="{{ item.quantity }}" readonly
                                   class="quantity_input">
                            <button
                                    type="button" class="quantity_plus"
                                    hx-post="{% url 'cart:update-item' item.id 'plus' %}"
                                    hx-swap="none"
                                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-qty-right"></i>
                            </button>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="item_sum">
                            <p>{{ item.item_total|floatformat:0 }} <span>{% trans "грн." %}</span></p>
                        </div>
                    </div>
                    <div class="col-1">
                        <div class="item_close">
                            <a
                                    href="#"
                                    hx-post="{% url 'cart:update-item' item.id 'remove' %}"
                                    hx-swap="none"
                                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            >
                                <i class="nut-icon icons-close-button"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="popup__cart_sum">
        <div class="sum_item">
            <div class="sum_item_title"><p>{% trans "Всего" %} </p></div>
            <div class="sum_item_new">
                <p>{{ cart.cart_total|floatformat:0 }} <i>{% trans "грн." %}</i></p>
            </div>
        </div>
        <div class="sum_item">
            <div class="sum_item_button">
                <a href="{% pageurl cart_page %}" class="button">{% trans "Перейти в корзину" %}</a>
            </div>
        </div>
    </div>
    {% else %}
    <div class="popup__cart_clean">
        <p>{% trans "Ваша корзина пуста" %}</p>
    </div>
    {% endif %}
</div>

templates/includes/cart/table.html
{% load wagtailcore_tags core_tags i18n %}
<div class="col-12">
    {% if cart and cart.items.all %}
    <table id="table">
        <thead>
        <tr>
            <th><span>{% trans "Товар" %}</span></th>
            <th><span>{% trans "Кол - во" %}</span></th>
            <th><span>{% trans "Цена за товар" %}</span></th>
            <th><span>{% trans "Итоговая стоимость" %}</span></th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart.items.all %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td>
                <div class="item_quantity">
                    <button
                            type="button" class="quantity_minus"
                            hx-post="{% url 'cart:update-item' item.id 'minus' %}"
                            hx-swap="none"
                            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    >
                        <i class="nut-icon icons-qty-left"></i>
                    </button>
                    <input type="text" name="quantity" value="{{ item.quantity }}" readonly class="quantity_input">
                    <button
                            type="button" class="quantity_plus"
                            hx-post="{% url 'cart:update-item' item.id 'plus' %}"
                            hx-swap="none"
                            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    >
                        <i class="nut-icon icons-qty-right"></i>
                    </button>
                </div>
            </td>
            <td>{{ item.actual_price|floatformat:0 }} {% trans "грн." %}</td>
            <td>{{ item.item_total|floatformat:0 }} {% trans "грн." %}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="text-center popup__cart_clean">
        <p>{% trans "Ваша корзина пуста" %}</p>
    </div>
    {% endif %}
</div>
<div class="col-12">
    <div class="after_table">
        <div class="row">
            <div class="col-md-6">
                <a href="{% pageurl shop_page %}" class="button_transparent with_arrow">
                    <i class="nut-icon icons-left-arrow"></i>
                    <b>{% trans "Продолжить покупки" %}</b>
                </a>
            </div>
            {% if cart and cart.items.all %}
            <div class="col-md-6">
                <div class="popup__cart_sum">
                    <div class="sum_item">
                        <div class="sum_item_title"><p>{% trans "Всего" %} </p></div>
                        <div class="sum_item_new">
                            <p>{{ cart.cart_total|floatformat:0 }} <i>{% trans "грн." %}</i></p>
                        </div>
                    </div>
                    {% if request.user.is_authenticated and request.user.customer_profile %}
                    <div class="sum_item">
                        <div class="sum_item_button">
                            <a href="{% pageurl checkout_page %}" class="button">{% trans "Оформить заказ" %}</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% if not request.user.is_authenticated or  not request.user.customer_profile %}
<div class="col-12">
    <div class="no_log-in">
        <h2>{% trans "Для оформления заказа необходимо" %}</h2>
        <div class="no_log-in_link">
            <a href="{% pageurl login_page %}">{% trans "Авторизоваться" %}</a>
            <span>{% trans "или" %}</span>
            <a href="{% pageurl register_page %}">{% trans "Зарегистрироваться" %}</a>
        </div>
    </div>
</div>
{% endif %}