nuts/auth/urls.py
from django.urls import path

from auth.views import (
    IndividualRegistrationView,
    BusinessRegistrationView,
    CustomerLoginView,
    CustomerForgotPasswordView,
    CustomerResetPasswordView,
    CustomerLogoutView
)

app_name = 'custom_auth'

urlpatterns = [
    path(
        route="registration/individual/",
        view=IndividualRegistrationView.as_view(),
        name="individual-registration"
    ),
    path(
        route="registration/business/",
        view=BusinessRegistrationView.as_view(),
        name="business-registration"
    ),
    path(
        route="login/",
        view=CustomerLoginView.as_view(),
        name="login"
    ),
    path(
        route="forgot-password/",
        view=CustomerForgotPasswordView.as_view(),
        name="forgot-password"
    ),
    path(
        route="reset-password/",
        view=CustomerResetPasswordView.as_view(),
        name="reset-password"
    ),
    path(
        route="logout/",
        view=CustomerLogoutView.as_view(),
        name="logout"
    )
]

templates/tags/auth_links.html
{% load i18n %}
{% if request.user.is_authenticated and request.user.customer_profile %}
<li>
    <a href="{{ profile_page.url }}"><i class="nut-icon icons-man-user"></i><span>{% trans "Профиль" %}</span></a>
</li>
<li>
    <form id="logout__button" method="POST" class="d-inline-block" action="{% url 'custom_auth:logout' %}">
        {% csrf_token %}
        <a href="#" onclick="document.getElementById('logout__button').submit()">
            <span>{% trans "Выйти" %}</span>
        </a>
    </form>
</li>
{% else %}
<li>
    <a href="{{ login_page.url }}"><i class="nut-icon icons-man-user"></i><span>{% trans "Вход" %}</span></a>
</li>
<li>
    <a href="{{ register_page.url }}"><span>{% trans "Регистрация" %}</span></a>
</li>
{% endif %}

templates/tags/breadcrumbs.html
{% if ancestors %}
<div class="breadcrumbs">
    <ul>
        {% for page in ancestors %}
        <li>
            {% if forloop.last %}
            {{ page.title }}
            {% else %}
            <a href="{{ page.url }}">{{ page.title }}</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

templates/tags/language_switcher.html
{% load i18n wagtail_modeltranslation %}
{% get_available_languages_wmt as languages %}
{% get_current_language as language_code %}

{% for language in languages %}
{% if language != language_code %}
<li>
    <a href="{% change_lang language page %}{% if query_parameters %}?{{ query_parameters }}{% endif %}">
        {{ language|capfirst }}
    </a>
</li>
{% endif %}
{% endfor %}

templates/tags/menu_links.html
{% load i18n %}
<li>
    {% if shop_page %}<a href="{{ shop_page.url }}">{{ shop_page.title }}</a>{% endif %}
</li>
<li>
    {% if about_page %}<a href="{{ about_page.url }}">{{ about_page.title }}</a>{% endif %}
</li>
<li>
    {% if delivery_page %}<a href="{{ delivery_page.url }}">{{ delivery_page.title }}</a>{% endif %}
</li>
<li>
    {% if customers_page %}<a href="{{ customers_page.url }}">{{ customers_page.title }}</a>{% endif %}
</li>
<li>
    {% if news_page %}<a href="{{ news_page.url }}">{{ news_page.title }}</a>{% endif %}
</li>
<li>
    <a href="#contacts">{% translate "Контакты" %}</a>
</li>

templates/tags/profile_menu_links.html
{% load i18n %}
<nav class="navigation">
    <p>{% trans "Мои заказы" %}</p>
    <ul>
        {% if orders_history_page %}
        <li>
            <a href="{{ orders_history_page.url }}"
               class="{% if current_page.id == orders_history_page.id %}active{% endif %}">
               {{ orders_history_page.title }}
            </a>
        </li>
        {% endif %}

        {% if transactions_history_page %}
        <li>
            <a href="{{ transactions_history_page.url }}"
               class="{% if current_page.id == transactions_history_page.id %}active{% endif %}">
               {{ transactions_history_page.title }}
            </a>
        </li>
        {% endif %}
    </ul>

    <p>{% trans "Моя учетная запись" %}</p>
    <ul>
        {% if contact_information_page %}
        <li>
            <a href="{{ contact_information_page.url }}"
               class="{% if current_page.id == contact_information_page.id %}active{% endif %}">
               {{ contact_information_page.title }}
            </a>
        </li>
        {% endif %}

        {% if change_password_page %}
        <li>
            <a href="{{ change_password_page.url }}"
               class="{% if current_page.id == change_password_page.id %}active{% endif %}">
                {{ change_password_page.title }}
            </a>
        </li>
        {% endif %}

        {% if address_page %}
        <li>
            <a href="{{ address_page.url }}"
               class="{% if current_page.id == address_page.id %}active{% endif %}">
               {{ address_page.title }}
            </a>
        </li>
        {% endif %}
    </ul>
</nav>