nuts/auth/urls.py
from django.urls import path

from auth.views import (
    IndividualRegistrationView,
    BusinessRegistrationView,
    CustomerLoginView,
    CustomerForgotPasswordView,
    CustomerResetPasswordView,
    CustomerLogoutView
)

app_name = 'custom_auth'

urlpatterns = [
    path(
        route="registration/individual/",
        view=IndividualRegistrationView.as_view(),
        name="individual-registration"
    ),
    path(
        route="registration/business/",
        view=BusinessRegistrationView.as_view(),
        name="business-registration"
    ),
    path(
        route="login/",
        view=CustomerLoginView.as_view(),
        name="login"
    ),
    path(
        route="forgot-password/",
        view=CustomerForgotPasswordView.as_view(),
        name="forgot-password"
    ),
    path(
        route="reset-password/",
        view=CustomerResetPasswordView.as_view(),
        name="reset-password"
    ),
    path(
        route="logout/",
        view=CustomerLogoutView.as_view(),
        name="logout"
    )
]

nuts/cart/urls.py
from django.urls import path

from cart.views import (
    CartAddItemView,
    CartUpdateItemView,
    CartPopupView,
    CartCounterView,
    CartTableView
)

app_name = 'cart'

urlpatterns = [
    path('add-item/<int:product_id>/', CartAddItemView.as_view(), name='add-item'),
    path('update-item/<int:item_id>/<str:action>', CartUpdateItemView.as_view(), name='update-item'),
    path('popup/', CartPopupView.as_view(), name='popup'),
    path('counter/', CartCounterView.as_view(), name='counter'),
    path('table/', CartTableView.as_view(), name='table')
]

nuts/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
]

nuts/shop/urls.py
from django.urls import path

from shop.views import ShopCatalogView

app_name = 'shop'

urlpatterns = [
    path(
        route="catalog/",
        view=ShopCatalogView.as_view(),
        name="catalog"
    )
]

nuts/about/models.py
import re

from django.db import models
from django.utils.text import Truncator

from wagtail.models import Page
from wagtail.fields import StreamField
from wagtail.admin.panels import FieldPanel
from wagtail.images.models import Image

from wagtailmedia.blocks import VideoChooserBlock

from core.blocks import VideoJumbotronBlock, ImageJumbotronBlock

from gallery.models import GalleryPage
from news.models import NewsIndexPage, NewsDetailPage


class AboutPage(Page):
    template = "about.html"

    parent_page_types = ['home.HomePage']
    subpage_types = []
    max_count = 1

    description = models.TextField(blank=True)

    hero = StreamField(
        [
            ("video_jumbotron", VideoJumbotronBlock()),
        ],
        blank=True,
        use_json_field=True,
        max_num=1
    )

    videos = StreamField([
        ('video', VideoChooserBlock())
    ], blank=True, use_json_field=True)

    owner_name = models.CharField(max_length=100, null=True, blank=True)
    owner_photo = models.ForeignKey(
        Image,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+"
    )
    owner_cite = models.CharField(max_length=255, blank=True)
    owner_description = models.TextField(blank=True)

    company_history_title = models.CharField(max_length=255, blank=True)
    company_history_description = models.TextField(blank=True)

    image_hero = StreamField(
        [
            ("image_jumbotron", ImageJumbotronBlock()),
        ],
        blank=True,
        use_json_field=True,
        max_num=1
    )

    content_panels = Page.content_panels + [
        FieldPanel("description"),
        FieldPanel("hero"),
        FieldPanel("videos"),
        FieldPanel("owner_name"),
        FieldPanel("owner_photo"),
        FieldPanel("owner_cite"),
        FieldPanel("owner_description"),
        FieldPanel("company_history_title"),
        FieldPanel("company_history_description"),
        FieldPanel("image_hero"),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)

        context["gallery_page"] = GalleryPage.objects.live().first()
        context["news_page"] = NewsIndexPage.objects.live().first()
        context["news_list"] = NewsDetailPage.objects.live().order_by('-publication_date')[:3]

        return context

    def short_description(self):
        if not self.description:
            return ""

        limit = 300

        if len(self.description) <= limit:
            return self.description

        match = re.match(r'^(.{300,Short?}.*?(\.|$))', self.description, re.DOTALL)

        if match:
            return match.group(1).strip()

        return Truncator(self.description).chars(limit + 50)

    class Meta:
        verbose_name = "About page"

nuts/cart/models.py
from django.db import models
from django.core.validators import MinValueValidator

from wagtail.models import Page

from cart.managers import CartManager

class CartPage(Page):
    parent_page_types = ['home.HomePage']
    subpage_types = ['orders.OrderCheckoutPage']
    max_count = 1

    template="cart.html"

    class Meta:
        verbose_name = "Cart page"


class Cart(models.Model):
    id = models.BigAutoField(primary_key=True)
    session_key = models.CharField(max_length=40, null=True, blank=True, db_index=True)
    customer = models.ForeignKey('users.CustomerProfile', on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CartManager()


class CartItem(models.Model):
    id = models.BigAutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey('products.Product', on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

nuts/customers/models.py
from django.db import models

from wagtail.models import Page
from wagtail.fields import StreamField, RichTextField
from wagtail.admin.panels import FieldPanel

from core.blocks import ImageJumbotronBlock

from .blocks import CustomerInfoBlock

class CustomersPage(Page):
    template = "customers.html"

    parent_page_types = ['home.HomePage']
    subpage_types = []
    max_count = 1

    hero = StreamField(
        [
            ('image_jumbotron', ImageJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    description_column_1 = RichTextField(blank=True)
    description_column_2 = RichTextField(blank=True)

    supermarkets = StreamField(
        [
            ('customer_info_block', CustomerInfoBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    retail_stores = StreamField(
        [
            ('customer_info_block', CustomerInfoBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    horeca = StreamField(
        [
            ('customer_info_block', CustomerInfoBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    fitness_clubs = StreamField(
        [
            ('customer_info_block', CustomerInfoBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    confectionary_bakeries = StreamField(
        [
            ('customer_info_block', CustomerInfoBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    image_hero = StreamField(
        [
            ('image_jumbotron', ImageJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    content_panels = Page.content_panels + [
        FieldPanel('hero'),
        FieldPanel('description_column_1'),
        FieldPanel('description_column_2'),
        FieldPanel('supermarkets'),
        FieldPanel('retail_stores'),
        FieldPanel('horeca'),
        FieldPanel('fitness_clubs'),
        FieldPanel('confectionary_bakeries'),
        FieldPanel('image_hero'),
    ]

nuts/gallery/models.py
from django.db import models
from django.core.paginator import Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page
from wagtail.fields import StreamField
from wagtail.admin.panels import FieldPanel

from wagtailmedia.blocks import VideoChooserBlock

from core.blocks import VideoJumbotronBlock

from .blocks import GalleryImageWithTextBlock


class GalleryPage(Page):
    template = "gallery.html"
    parent_page_types = ['home.HomePage']
    subpage_types = []
    max_count = 1

    hero = StreamField(
        [
            ('video_jumbotron', VideoJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1
    )

    subtitle = models.CharField(
        max_length=255,
        blank=True,
    )

    content = StreamField(
        [
            ('video', VideoChooserBlock()),
            ('image_with_text', GalleryImageWithTextBlock()),
            ('video_jumbotron', VideoJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
    )

    content_panels = Page.content_panels + [
        FieldPanel('subtitle'),
        FieldPanel('hero'),
        FieldPanel('content'),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)

        all_blocks = self.content

        paginator = Paginator(all_blocks, 5)
        page_number = request.GET.get('page', 1)
        blocks_page = paginator.get_page(page_number)

        context['blocks'] = blocks_page
        return context

    def serve(self, request, *args, **kwargs):
        if request.headers.get('HX-Request'):
            context = self.get_context(request)

            return TemplateResponse(
                request,
                "includes/gallery/blocks.html",
                context
            )
        # Звичайний запит
        return super().serve(request)

    class Meta:
        verbose_name = "Gallery page"

nuts/payment_and_delivery/models.py
from django.db import models

from wagtail.models import Page
from wagtail.fields import StreamField
from wagtail.admin.panels import FieldPanel

from core.blocks import VideoJumbotronBlock, ImageJumbotronBlock

from .blocks import PaymentAndDeliveryInfoSectionBlock


class PaymentAndDeliveryPage(Page):
    template = "payment_and_delivery.html"

    parent_page_types = ['home.HomePage']
    subpage_types = []
    max_count = 1

    image_hero = StreamField(
        [
            ('image_jumbotron', ImageJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    payment_info = StreamField(
        [
            ('info_section_block', PaymentAndDeliveryInfoSectionBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    delivery_info = StreamField(
        [
            ('info_section_block', PaymentAndDeliveryInfoSectionBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    return_info = StreamField(
        [
            ('info_section_block', PaymentAndDeliveryInfoSectionBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    video_hero = StreamField(
        [
            ('video_jumbotron', VideoJumbotronBlock()),
        ],
        use_json_field=True,
        blank=True,
        max_num=1,
    )

    content_panels = Page.content_panels + [
        FieldPanel('image_hero'),
        FieldPanel('payment_info'),
        FieldPanel('delivery_info'),
        FieldPanel('return_info'),
        FieldPanel('video_hero')
    ]

    class Meta:
        verbose_name = "Payment and delivery page"

nuts/shop/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from products.models import ProductFeature

class ProductFilterForm(forms.Form):
    feature = forms.ModelChoiceField(
        queryset=ProductFeature.objects.all(),
        empty_label=_("Вкус"),
        required=False,
    )

    WEIGHT_CHOICES = [
        ('', _("Масса")),
        ('0-50', _("от 0 до 50 г")),
        ('50-100', _("от 50 до 100 г")),
        ('100-200', _("от 100 до 200 г")),
        ('200-400', _("от 200 до 400 г")),
        ('400-9999', _("от 400 г")),
    ]
    weight_range = forms.ChoiceField(
        choices=WEIGHT_CHOICES,
        required=False
    )

    sort_price = forms.ChoiceField(
        choices=[
            ('asc', _("По возрастанию")),
            ('desc', _("По убыванию"))
        ],
        required=False,
        widget=forms.HiddenInput()
    )

nuts/cart/views.py
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render

from products.models import Product

from cart.models import Cart, CartItem

from shop.models import ShopPage

from auth.models import RegisterPage, LoginPage

from orders.models import OrderCheckoutPage

class CartAddItemView(View):
    def post(self, request, product_id):
        product = Product.objects.get(id=product_id)

        if request.user.is_authenticated and hasattr(request.user, "customer_profile"):
            cart, _ = Cart.objects.get_or_create(
                customer=request.user.customer_profile,
                is_active=True,
            )
        else:
            if not request.session.session_key:
                request.session.create()
            cart, _ = Cart.objects.get_or_create(
                session_key=request.session.session_key,
                is_active=True
            )

        item, created = CartItem.objects.get_or_create(cart=cart, product=product, defaults={'quantity': 1})

        if not created:
            item.quantity += 1
            item.save()
        else:
            item.quantity = 1
            item.save()

        response = HttpResponse()
        response['HX-Trigger'] = 'cartUpdated'
        return response


class CartUpdateItemView(View):
    def post(self, request, item_id, action):
        item = CartItem.objects.get(id=item_id)

        if action == 'plus':
            item.quantity += 1
            item.save()

        elif action == 'minus':
            if item.quantity > 1:
                item.quantity -= 1
                item.save()
            else:
                item.delete()

        elif action == 'remove':
            item.delete()

        response = HttpResponse()
        response['HX-Trigger'] = 'cartUpdated'
        return response


class CartPopupView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)
        return render(request, "includes/cart/popup_content.html", {"cart": cart})


class CartCounterView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)
        count = getattr(cart, 'cart_items_count', 0) or 0
        return HttpResponse(str(count))


class CartTableView(View):
    def get(self, request):
        cart = Cart.objects.get_cart_with_totals(request)

        shop_page = ShopPage.objects.live().first()
        login_page = LoginPage.objects.live().first()
        register_page = RegisterPage.objects.live().first()
        checkout_page = OrderCheckoutPage.objects.live().first()

        return render(
            request,
            "includes/cart/table.html",
            {
                "cart": cart,
                "shop_page": shop_page,
                "login_page": login_page,
                "register_page": register_page,
                "checkout_page": checkout_page
            }
        )

nuts/shop/views.py
from django.views import View
from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import Case, When, F, DecimalField
from products.models import Product, ProductPage

from .forms import ProductFilterForm

class ShopCatalogView(View):
    def get(self, request, *args, **kwargs):
        queryset = Product.objects.all().prefetch_related('images', 'features')

        form = ProductFilterForm(request.GET)
        if form.is_valid():
            feature = form.cleaned_data.get('feature')

            if feature:
                queryset = queryset.filter(features=feature)

            weight_range = form.cleaned_data.get('weight_range')

            if weight_range:
                try:
                    w_min, w_max = weight_range.split('-')
                    queryset = queryset.filter(weight__gte=w_min, weight__lte=w_max)
                except ValueError:
                    pass

            queryset = queryset.annotate(
                actual_price=Case(
                    When(discounted_price__isnull=False, then=F('discounted_price')),
                    default=F('price'),
                    output_field=DecimalField(),
                )
            )

            sort = form.cleaned_data.get('sort_price')

            if sort == 'asc':
                queryset = queryset.order_by('actual_price')
            elif sort == 'desc':
                queryset = queryset.order_by('-actual_price')

        paginator = Paginator(queryset, 1)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        product_page = ProductPage.objects.live().first()

        context = {
            'products': page_obj,
            'page_obj': page_obj,
            'product_page': product_page,
            'filter_form': form
        }

        return render(request, "includes/shop/cards.html", context)

templates/cart.html
{% extends "base.html" %}
{% load wagtailimages_tags core_tags i18n %} {% block content %}
<section class="first-section no-bg">
    <div class="container">
        {% breadcrumbs %}
    </div>
</section>

<section
        class="accaunt"
        hx-get="{% url 'cart:table' %}"
        hx-trigger="load, cartUpdated from:body"
        hx-target="#cart__table__wrapper"
>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h1>{{ page.title }}</h1>
            </div>
            <div class="col-lg-9 col-md-6">
                <div class="accaunt__manager">
                    <ul>
                        <li>
                            <p>
                                {% blocktrans with manager_name=settings.core.ContactSettings.manager_name %}
                                    Ваш личный менеджер {{ manager_name }}
                                {% endblocktrans %}
                            </p>
                        </li>
                        <li><i class="nut-icon icons-phone"></i>
                            <a href="tel:{{ settings.core.ContactSettings.manager_phone|clean_phone }}">
                                {{ settings.core.ContactSettings.manager_phone }}
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="cart__table__wrapper" class="col-12">
                </div>
        </div>
    </div>
</section>
{% endblock %}

templates/checkout.html
{% extends "base.html" %}
{% load wagtailimages_tags core_tags i18n %} {% block content %}
<section class="first-section no-bg">
    <div class="container">
        {% breadcrumbs %}
    </div>
</section>

<section class="accaunt ">
    <div class="container">
        <form class="order_checkout__form" action="{% url 'orders:create' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <h1>{{page.title}}</h1>
                </div>
                <div class="col-lg-8 col-md-6">
                    <div class="accaunt__manager">
                        <ul>
                            <li>
                                <p>
                                    {% blocktrans with manager_name=settings.core.ContactSettings.manager_name %}
                                        Ваш личный менеджер {{ manager_name }}
                                    {% endblocktrans %}
                                </p>
                            </li>
                            <li><i class="nut-icon icons-phone"></i>
                                <a href="tel:{{ settings.core.ContactSettings.manager_phone|clean_phone }}">
                                    {{ settings.core.ContactSettings.manager_phone }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-12">
                    <table id="table">
                        <thead>
                        <tr>
                            <th><span>{% trans "Товар" %}</span></th>
                            <th><span>{% trans "Кол - во" %}</span></th>
                            <th><span>{% trans "Цена за товар" %}</span></th>
                            <th><span>{% trans "Итоговая стоимость" %}</span></th>
                        </tr>
                        </thead>
                        <tbody>
                        {{ formset.management_form }}

                        {% for item_form in formset %}
                        <tr class="order_item__row">
                            <td>
                                {{ item_form.id }}
                                {{ item_form.product }}
                                {{ item_form.price }}
                                {{ item_form.initial.product.name }}
                            </td>
                            <td>
                                <div class="item_quantity">
                                    <button type="button" class="quantity_minus">
                                        <i class="nut-icon icons-qty-left"></i>
                                    </button>
                                    {{ item_form.quantity }}
                                    <button type="button" class="quantity_plus">
                                        <i class="nut-icon icons-qty-right"></i>
                                    </button>
                                </div>
                            </td>
                            <td><span class="order_item__row__price">{{ item_form.initial.price|floatformat:0 }}</span> {% trans "грн." %}</td>
                            <td>
                                <span class="item_total order_item__row__total_price">
                                    {% widthratio item_form.initial.price 1 item_form.initial.quantity %} {% trans "грн." %}
                                </span>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12">
                    <div class="after_table">
                        <div class="row">
                            <div class="col-md-6"></div>
                            <div class="col-md-6">
                                <div class="popup__cart_sum">
                                    <div class="sum_item">
                                        <div class="sum_item_title">
                                            <p>{% trans "Всего" %}</p>
                                        </div>
                                        <div class="sum_item_new">
                                            <p><span class="order__total_price">{{ cart.cart_total|floatformat:0 }}</span> <i>{% trans "грн." %}</i></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="checkout_form">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form__title">
                                    {% trans "1. Контактные данные" %}
                                </div>
                                {% if request.user.customer_profile.business_profile %}
                                {{ form.company_name }}
                                {{ form.contact_person }}
                                {% else %}
                                {{ form.full_name }}
                                {% endif %}
                                {{ form.email }}
                                {{ form.phone }}

                                <div class="form__title">{% trans "2. Способ доставки" %}</div>
                                <fieldset id="group1" class="radio__wrapper radio__wrapper_click">
                                    {% for choice in form.delivery_method %}
                                    <input
                                            id="radio-{{ forloop.counter }}"
                                            class="radio-custom"
                                            name="{{ form.delivery_method.name }}"
                                            value="{{ choice.data.value }}"
                                            type="radio"
                                            {% if choice.data.selected %}checked{% endif %}
                                    >

                                    <label
                                            for="radio-{{ forloop.counter }}"
                                            class="radio-custom-label {% if forloop.last %}radio-custom_last{% endif %}"
                                    >
                                        <span>{{ choice.choice_label }}</span>
                                        {% if choice.data.value == 'COURIER' %}
                                        <span class="sticker">
                                            <i class="nut-icon icons-novinka"></i>
                                            <span class="p">{% trans "БЕСПЛАТНО" %}</span>
                                        </span>
                                        {% endif %}
                                    </label>

                                    {% if choice.data.value == 'NOVA_POSHTA' %}
                                    <div class="NOVA_POSHTA box" {% if not choice.data.selected %} style="display: none" {% endif %}>
                                        {{ form.delivery_country }}
                                        {{ form.delivery_region }}
                                    </div>
                                    {% endif %}

                                    {% if choice.data.value == 'COURIER' %}
                                    <div class="COURIER box" {% if not choice.data.selected %} style="display: none" {% endif %}>
                                        {{ form.delivery_address }}
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                </fieldset>

                                <div class="form__title">
                                    {% trans "3. Способ оплаты" %}
                                </div>
                                <fieldset id="group2" class="radio__wrapper radio__wrapper_second">
                                    {% for choice in form.payment_method %}
                                    <input id="radio-{{ forloop.counter|add:3 }}"
                                           class="radio-custom"
                                           name="{{ form.payment_method.name }}"
                                           value="{{ choice.data.value }}"
                                           type="radio"
                                           {% if choice.data.selected %}checked{% endif %}>

                                    <label for="radio-{{ forloop.counter|add:3 }}" class="radio-custom-label">
                                        <span>{{ choice.choice_label }}</span>
                                    </label>
                                    {% endfor %}
                                </fieldset>
                                <button class="button float-left" type="submit">{% trans "Продолжить" %}</button>
                            </div>
                            <div class="col-lg-7"></div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/shop.html
{% extends "base.html" %}
{% load wagtailcore_tags wagtailimages_tags core_tags i18n %}
{% block content %}
{% with block=page.hero.0 %}
{% image block.value.background_image original as bg_image %}
<section class="first-section overlay" style="background-image: url('{{ bg_image.url }}')">
    <div class="container">
        {% breadcrumbs %}
        <div class="row align-items-center justify-content-center">
            <h1>{{ block.value.title }}</h1>
        </div>
    </div>
</section>
<section class="production">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12">
                <div class="production__filter">
                    <form
                            id="filter-form"
                            hx-get="{% url 'shop:catalog' %}"
                            hx-target="#product-grid"
                    >
                        {% csrf_token %}
                        <div id="filter-form-inner">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div
                class="row justify-content-center"
                id="product-grid"
                hx-get="{% url 'shop:catalog' %}"
                hx-trigger="load"
                hx-include="#filter-form"
        >
        </div>
        <div id="load-more-wrapper">
        </div>
    </div>
    </div>
</section>
<section class="manufacturer gray_section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-5">
                <h2>{{ page.nut_title }}</h2>
                <div class="wrapper">
                    <p>{{ page.nut_description }}</p>
                </div>
            </div>
            <div class="col-md-7">
                <div class="manufacturer-container swiper-container">
                    <div class="swiper-wrapper">
                        {% for slide in page.gallery %}
                        {% image slide.value original as img %}
                        <div class="swiper-slide">
                            <div class="manufacturer__item">
                                <img src="{{img.url}}" alt="{% trans 'Gallery Slide' %}">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="wrap">
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endwith %}
{% endblock %}